name: Android CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK (17 for AGP 8+; use 11 if you're old-school)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      # If you use the Android CI template it’ll auto-install cmdline-tools.
      # For some projects you might still want to be explicit:
      - name: Install Android SDK components
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      - name: Print Gradle & AGP versions (debugging vibes)
        run: ./gradlew -v

      - name: Run unit tests + Lint
        run: ./gradlew testDebugUnitTest lint

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
